//
//  ultimateTicTacToeViewController.h
//  ultimateTicTacToe
//
//  Created by Steven Grutman on 11/30/12.
//  Copyright (c) 2012 Steven Grutman. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <iAd/iAd.h>

@interface ultimateTicTacToeViewController : UIViewController {
    
    IBOutlet UIButton *lines1;
    IBOutlet UIButton *lines2;
    IBOutlet UIButton *lines3;
    IBOutlet UIButton *lines4;
    IBOutlet UIButton *lines5;
    IBOutlet UIButton *lines6;
    IBOutlet UIButton *lines7;
    IBOutlet UIButton *lines8;
    IBOutlet UIButton *lines9;
    IBOutlet UIButton *lines10;
    IBOutlet UIButton *lines11;
    IBOutlet UIButton *lines12;
    IBOutlet UIButton *lines13;
    IBOutlet UIButton *lines14;
    IBOutlet UIButton *lines15;
    IBOutlet UIButton *lines16;
    IBOutlet UIButton *lines17;
    IBOutlet UIButton *lines18;
    IBOutlet UIButton *lines19;
    IBOutlet UIButton *lines20;
    IBOutlet UIButton *lines21;
    IBOutlet UIButton *lines22;
    IBOutlet UIButton *lines23;
    IBOutlet UIButton *lines24;
    IBOutlet UIButton *lines25;
    IBOutlet UIButton *lines26;
    IBOutlet UIButton *lines27;
    IBOutlet UIButton *lines28;
    IBOutlet UIButton *lines29;
    IBOutlet UIButton *lines30;
    IBOutlet UIButton *lines31;
    IBOutlet UIButton *lines32;
    IBOutlet UIButton *lines33;
    IBOutlet UIButton *lines34;
    IBOutlet UIButton *lines35;
    IBOutlet UIButton *lines36;
    int twoPlayer;
    IBOutlet UIButton *reset1;
     IBOutlet UIButton *reset2;
     IBOutlet UIButton *reset3;
    int ooo;
    NSString *idkk;
    UIButton *cbd;
    int cbdi;
    int blahDos;
    int blah;
    int aaa;
    UIButton *abc;
    UIButton *check;
    int bcd;
    int pizza;
    int a12345;
    int a1;
    int a2;
    int a3;
    int a4;
    int a5;
    int a6;
    int a7;
    int a8;
    int a9;
    int a10;
    int a11;
    int a12;
    int a13;
    int a14;
    int a15;
    int a16;
    int a17;
    int a18;
    int a19;
    int a20;
    int a21;
    int a22;
    int a23;
    int a24;
    int a25;
    int a26;
    int a27;
    int a28;
    int a29;
    int a30;
    int a31;
    int a32;
    int a33;
    int a34;
    int a35;
    int a36;
    int a37;
    int a38;
    int a39;
    int a40;
    int a41;
    int a42;
    int a43;
    int a44;
    int a45;
    int a46;
    int a47;
    int a48;
    int a49;
    int a50;
    int a51;
    int a52;
    int a53;
    int a54;
    int a55;
    int a56;
    int a57;
    int a58;
    int a59;
    int a60;
    int a61;
    int a62;
    int a63;
    int a64;
    int a65;
    int a66;
    int a67;
    int a68;
    int a69;
    int a70;
    int a71;
    int a72;
    int a73;
    int a74;
    int a75;
    int a76;
    int a77;
    int a78;
    int a79;
    int a80;
    int a81;
    int b1;
    int b2;
    int b3;
    int b4;
    int b5;
    int b6;
    int b7;
    int b8;
    int b9;
    IBOutlet UIButton *space1;
    IBOutlet UIButton *space2;
    IBOutlet UIButton *space3;
    IBOutlet UIButton *space4;
    IBOutlet UIButton *space5;
    IBOutlet UIButton *space6;
    IBOutlet UIButton *space7;
    IBOutlet UIButton *space8;
    IBOutlet UIButton *space9;
    IBOutlet UIButton *space10;
    IBOutlet UIButton *space11;
    IBOutlet UIButton *space12;
    IBOutlet UIButton *space13;
    IBOutlet UIButton *space14;
    IBOutlet UIButton *space15;
    IBOutlet UIButton *space16;
    IBOutlet UIButton *space17;
    IBOutlet UIButton *space18;
    IBOutlet UIButton *space19;
    IBOutlet UIButton *space120;
    IBOutlet UIButton *space121;
    IBOutlet UIButton *space122;
    IBOutlet UIButton *space123;
    IBOutlet UIButton *space124;
    IBOutlet UIButton *space125;
    IBOutlet UIButton *space126;
    IBOutlet UIButton *space127;
    IBOutlet UIButton *space128;
    IBOutlet UIButton *space129;
    IBOutlet UIButton *space130;
    IBOutlet UIButton *space131;
    IBOutlet UIButton *space132;
    IBOutlet UIButton *space133;
    IBOutlet UIButton *space134;
    IBOutlet UIButton *space135;
    IBOutlet UIButton *space136;
    IBOutlet UIButton *space137;
    IBOutlet UIButton *space138;
    IBOutlet UIButton *space139;
    IBOutlet UIButton *space140;
    IBOutlet UIButton *space141;
    IBOutlet UIButton *space142;
    IBOutlet UIButton *space143;
    IBOutlet UIButton *space144;
    IBOutlet UIButton *space145;
    IBOutlet UIButton *space146;
    IBOutlet UIButton *space147;
    IBOutlet UIButton *space148;
    IBOutlet UIButton *space149;
    IBOutlet UIButton *space150;
    IBOutlet UIButton *space151;
    IBOutlet UIButton *space152;
    IBOutlet UIButton *space153;
    IBOutlet UIButton *space154;
    IBOutlet UIButton *space155;
    IBOutlet UIButton *space156;
    IBOutlet UIButton *space157;
    IBOutlet UIButton *space158;
    IBOutlet UIButton *space159;
    IBOutlet UIButton *space160;
    IBOutlet UIButton *space161;
    IBOutlet UIButton *space162;
    IBOutlet UIButton *space163;
    IBOutlet UIButton *space164;
    IBOutlet UIButton *space165;
    IBOutlet UIButton *space166;
    IBOutlet UIButton *space167;
    IBOutlet UIButton *space168;
    IBOutlet UIButton *space169;
    IBOutlet UIButton *space170;
    IBOutlet UIButton *space171;
    IBOutlet UIButton *space172;
    IBOutlet UIButton *space173;
    IBOutlet UIButton *space174;
    IBOutlet UIButton *space175;
    IBOutlet UIButton *space176;
    IBOutlet UIButton *space177;
    IBOutlet UIButton *space178;
    IBOutlet UIButton *space179;
    IBOutlet UIButton *space180;
    IBOutlet UIButton *space181;
    IBOutlet UIButton *space182;
    IBOutlet UIButton *space183;
    IBOutlet UIButton *space184;
    IBOutlet UIButton *space185;
    IBOutlet UIButton *space186;
    IBOutlet UIButton *space187;
    IBOutlet UIButton *space188;
    IBOutlet UIButton *space189;
    IBOutlet UIButton *space190;
    IBOutlet UIButton *cursor;
    IBOutlet UILabel *label;
    UIButton *go;
    UIButton *going;
    UIButton *going2;
    UIButton *going3;
    int gone;
    int hh;
    int ii;
    int jj;
    int gg;
    int win;
    int person;
    int xwins;
    int owins;
    int games;
    int draws;
    NSArray * buttons;
    NSArray * big;
    int cbig;
    UIButton *cbigb;
    UIButton *fun;
    int funny;
    int kk;
    UIButton *going4;
    int strategy;
    int gos;
    int bbbb;
    UIButton *cccc;
    int y1;
    int y2;
    int y3;
    int y4;
    int y5;
    int y6;
    UIButton *going5;
    UIButton *going6;
    UIButton *going7;
    UIButton *going8;
    UIButton *going9;
    UIButton *going10;
    int ppp;
    int qqq;
    int rrr;
    int sss;
    int ttt;
    int uuu;
    int vvv;
    IBOutlet UIButton *cover;
    //no used yet (hopefull gonna b used in while)
    
}



-(IBAction)reset1;
-(IBAction)reset2;
-(IBAction)reset3;
-(IBAction)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event;
-(IBAction)like;
-(IBAction)twitter;

@end
