//
//  sudokuViewController.h
//  sudoku
//
//  Created by Steven Grutman on 1/9/13.
//  Copyright (c) 2013 Steven Grutman. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface sudokuViewController : UIViewController{
   
    IBOutlet UIProgressView *prog;
    int counter4;
    NSTimer * set;
    int dubs;
    int aa;
    int bb;
    int cc;
    int dd;
    int ee;
    IBOutlet UIButton *space1;
    IBOutlet UIButton *space2;
    IBOutlet UIButton *space3;
    IBOutlet UIButton *space4;
    IBOutlet UIButton *space5;
    IBOutlet UIButton *space6;
    IBOutlet UIButton *space7;
    IBOutlet UIButton *space8;
    IBOutlet UIButton *space9;
    IBOutlet UIButton *space10;
    IBOutlet UIButton *space11;
    IBOutlet UIButton *space12;
    IBOutlet UIButton *space13;
    IBOutlet UIButton *space14;
    IBOutlet UIButton *space15;
    IBOutlet UIButton *space16;
    IBOutlet UIButton *space17;
    IBOutlet UIButton *space18;
    IBOutlet UIButton *space19;
    IBOutlet UIButton *space120;
    IBOutlet UIButton *space121;
    IBOutlet UIButton *space122;
    IBOutlet UIButton *space123;
    IBOutlet UIButton *space124;
    IBOutlet UIButton *space125;
    IBOutlet UIButton *space126;
    IBOutlet UIButton *space127;
    IBOutlet UIButton *space128;
    IBOutlet UIButton *space129;
    IBOutlet UIButton *space130;
    IBOutlet UIButton *space131;
    IBOutlet UIButton *space132;
    IBOutlet UIButton *space133;
    IBOutlet UIButton *space134;
    IBOutlet UIButton *space135;
    IBOutlet UIButton *space136;
    IBOutlet UIButton *space137;
    IBOutlet UIButton *space138;
    IBOutlet UIButton *space139;
    IBOutlet UIButton *space140;
    IBOutlet UIButton *space141;
    IBOutlet UIButton *space142;
    IBOutlet UIButton *space143;
    IBOutlet UIButton *space144;
    IBOutlet UIButton *space145;
    IBOutlet UIButton *space146;
    IBOutlet UIButton *space147;
    IBOutlet UIButton *space148;
    IBOutlet UIButton *space149;
    IBOutlet UIButton *space150;
    IBOutlet UIButton *space151;
    IBOutlet UIButton *space152;
    IBOutlet UIButton *space153;
    IBOutlet UIButton *space154;
    IBOutlet UIButton *space155;
    IBOutlet UIButton *space156;
    IBOutlet UIButton *space157;
    IBOutlet UIButton *space158;
    IBOutlet UIButton *space159;
    IBOutlet UIButton *space160;
    IBOutlet UIButton *space161;
    IBOutlet UIButton *space162;
    IBOutlet UIButton *space163;
    IBOutlet UIButton *space164;
    IBOutlet UIButton *space165;
    IBOutlet UIButton *space166;
    IBOutlet UIButton *space167;
    IBOutlet UIButton *space168;
    IBOutlet UIButton *space169;
    IBOutlet UIButton *space170;
    IBOutlet UIButton *space171;
    IBOutlet UIButton *space172;
    IBOutlet UIButton *space173;
    IBOutlet UIButton *space174;
    IBOutlet UIButton *space175;
    IBOutlet UIButton *space176;
    IBOutlet UIButton *space177;
    IBOutlet UIButton *space178;
    IBOutlet UIButton *space179;
    IBOutlet UIButton *space180;
    IBOutlet UIButton *space181;

    UILabel *lspace1;
    UILabel *lspace2;
    UILabel *lspace3;
   UILabel *lspace4;
    UILabel *lspace5;
    UILabel *lspace6;
   UILabel *lspace7;
    UILabel *lspace8;
    UILabel *lspace9;
    UILabel *lspace10;
    UILabel *lspace11;
    UILabel *lspace12;
    UILabel *lspace13;
   UILabel *lspace14;
    UILabel *lspace15;
    UILabel *lspace16;
    UILabel *lspace17;
    UILabel *lspace18;
    UILabel *lspace19;
    UILabel *lspace120;
    UILabel *lspace121;
    UILabel *lspace122;
    UILabel *lspace123;
    UILabel *lspace124;
    UILabel *lspace125;
    UILabel *lspace126;
   UILabel *lspace127;
    UILabel *lspace128;
    UILabel *lspace129;
    UILabel *lspace130;
    UILabel *lspace131;
    UILabel *lspace132;
    UILabel *lspace133;
    UILabel *lspace134;
    UILabel *lspace135;
    UILabel *lspace136;
    UILabel *lspace137;
    UILabel *lspace138;
    UILabel *lspace139;
    UILabel *lspace140;
    UILabel *lspace141;
    UILabel *lspace142;
    UILabel *lspace143;
    UILabel *lspace144;
    UILabel *lspace145;
    UILabel *lspace146;
    UILabel *lspace147;
    UILabel *lspace148;
    UILabel *lspace149;
    UILabel *lspace150;
    UILabel *lspace151;
    UILabel *lspace152;
    UILabel *lspace153;
    UILabel *lspace154;
    UILabel *lspace155;
    UILabel *lspace156;
    UILabel *lspace157;
    UILabel *lspace158;
    UILabel *lspace159;
    UILabel *lspace160;
    UILabel *lspace161;
    UILabel *lspace162;
    UILabel *lspace163;
   UILabel *lspace164;
    UILabel *lspace165;
    UILabel *lspace166;
   UILabel *lspace167;
    UILabel *lspace168;
    UILabel *lspace169;
    UILabel *lspace170;
    UILabel *lspace171;
    UILabel *lspace172;
    UILabel *lspace173;
    UILabel *lspace174;
    UILabel *lspace175;
    UILabel *lspace176;
    UILabel *lspace177;
    UILabel *lspace178;
    UILabel *lspace179;
    UILabel *lspace180;
    UILabel *lspace181;
    UIButton *button;

    
    int gg;
    UIButton *go;
    IBOutlet UIButton *cursor;
    NSArray * buttons;
    NSArray * row1;
     NSArray * row2;
     NSArray * row3;
     NSArray * row4;
     NSArray * row5;
     NSArray * row6;
     NSArray * row7;
     NSArray * row8;
     NSArray * row9;
     NSArray * column1;
    NSArray * column2;
    NSArray * column3;
    NSArray * column4;
    NSArray * column5;
    NSArray * column6;
    NSArray * column7;
    NSArray * column8;
    NSArray * column9;
    NSArray * box1;
       NSArray * box2;
       NSArray * box3;
       NSArray * box4;
       NSArray * box5;
       NSArray * box6;
       NSArray * box7;
       NSArray * box8;
       NSArray * box9;
    int check;
    int check2;
    UIButton *checkB;
    UIButton *checkB2;
    int rand;
    int counter;
    int rand2;
    int counter2;
    int checked;
    int counter3;
    IBOutlet UIButton *choice1;
    IBOutlet UIButton *choice2;
    IBOutlet UIButton *choice3;
    IBOutlet UIButton *choice4;
    IBOutlet UIButton *choice5;
    IBOutlet UIButton *choice6;
    IBOutlet UIButton *choice7;
    IBOutlet UIButton *choice8;
    IBOutlet UIButton *choice9;
    int hh;
    int check3;
    int check4;
    int rand3;
    int check5;

}

-(IBAction)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event;
-(IBAction)reset;
-(IBAction)chose1;
-(IBAction)chose2;
-(IBAction)chose3;
-(IBAction)chose4;
-(IBAction)chose5;
-(IBAction)chose6;
-(IBAction)chose7;
-(IBAction)chose8;
-(IBAction)chose9;

@end
